name: Release application

env:
  APPLICATION_JAR_FOLDER: ./build/libs/
  APPLICATION_JAR_NAME: vega

on:
  workflow_dispatch:
  pull_request:
#  push:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout a current branch
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISRTIBUTION }}
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
      - name: Build jar with Gradle
        run: gradle jar
      - name: Get jar version
        run: echo "JAR_VERSION=$(unzip -p ${{ env.APPLICATION_JAR_FOLDER }}${{ env.APPLICATION_JAR_NAME }}.jar META-INF/MANIFEST.MF | grep 'Implementation-Version' | cut -d':' -f2 | tr -d "[:space:]")" >> $GITHUB_ENV
      - name: Create Release File
        run: cp ${{ env.APPLICATION_JAR_FOLDER }}${{ env.APPLICATION_JAR_NAME }}.jar ${{ env.APPLICATION_JAR_FOLDER }}${{ env.APPLICATION_JAR_NAME }}-${{ env.JAR_VERSION }}.jar
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ github.event.head_commit.message }}
          prerelease: true
          tag_name: ${{ env.JAR_VERSION }}
          files: |
            ${{ env.APPLICATION_JAR_FOLDER }}${{ env.JAR_FILE_NAME }}-${{ env.JAR_VERSION }}.jar
